name: CI

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  run_tracker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: false

      - name: Run tracker
        env:
          bottoken: ${{ secrets.BOTTOKEN }}
        run: uv run aosp_tracker.py --send-telegram --push
